name: Azure App Service Deployment
 
on: # defined to trigger the jobs of the workflow
 workflow_dispatch:

jobs:
  azure-app-service:
    name: php-app-deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checking if App Service Exists
        run: |
          if ! az webapp list --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} | grep -q '"name": "kkphp"'; then
             echo "App service doesnot exists. Creating it.."
             az webapp create --name ${{ vars.AZURE_APP_SERVICE_NAME }} --plan ${{ vars.AZURE_APP_SERVICE_PLAN }} --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --runtime "php|8.3"
          else
             echo "App service already exists. Skipping Creation..."
          fi
          sleep 10

             # To Create "Staging" Deployment slot 
      - name: Creating a staging Deployment slot
        run: |
          if ! az webapp deployment slot list --name ${{ vars.AZURE_APP_SERVICE_NAME }} --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} | grep -q '"name": "staging"'; then
             echo "Deployment slot "staging" not exists. Creating it.."
             az webapp deployment slot create --name ${{ vars.AZURE_APP_SERVICE_NAME }} --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --slot ${{ vars.SLOT_NAME }}
          else
             echo "Staging slot exists. Skipping Creation..."
          fi
          sleep 10

        # To check the App Service Publish Profile
      - name: Get App service Publish profile
        run: |
          az webapp deployment list-publishing-profiles --name ${{ vars.AZURE_APP_SERVICE_NAME }} \
          --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
          --xml 

      # This Job is to Build the Artfiacts by using repository.
  build-php-app:
     name: build-php-app
     runs-on: ubuntu-latest
     needs: [azure-app-service] # maintains the dependency of the previous job in current job
     steps:
       - name: Setup PHP
         uses: shivammathur/setup-php@v2
         with:
           php-version: '8.3'
 
       # To upload the artifacts in the current directory
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
         with:
           name: php-app
           path: .

 # This job is to deploy the artifacts in staging slot
  deploying-artifacts-in-staging-slot:
      name: Deploy Artifacts into staging slot
      needs: [azure-app-service, build-php-app]
      runs-on: ubuntu-latest
      steps:
        # To download the artifacts from the build job
        - name: Download artifact from build job
          uses: actions/download-artifact@v4
          with:
            name: php-app    

          # To get the URL of Staging Slot
        - name: Get App Service URL of staging slot
          run: |
            echo "App Service URL (Staging Slot): https://${{ vars.AZURE_APP_SERVICE_NAME }}-staging.azurewebsites.net"

  # This job is to deploy the artifacts in production slot with the reviewer's approval
  deploying-artifacts-in-production-slot:
     name: Deploy Artifacts into Production Slot
     runs-on: self-hosted
     needs: [azure-app-service, build-php-app, deploying-artifacts-in-staging-slot]
     environment:
       name: Prod
     steps:
       # To wait for the approval to deploy in production slot
       - name: Approval Status
         run: |
           printf "Approval done. Ready to deploy artifacts in Production..."
           sleep 5

       # Download the artifacts from the build job
       - name: Download artifact from build job
         uses: actions/download-artifact@v4
         with:
           name: php-app

       # To Deploy the artifacts in Production slot
       - name: Deploying Artifacts to Production Slot
         uses: azure/webapps-deploy@v2
         with:
            app-name: ${{ vars.AZURE_APP_SERVICE_NAME }}
            slot-name: production
            package: . # represents the current directory

       # To get the URL of Production slot
       - name: Get App Service URL of Production slot
         run: |
            echo "App Service URL (Production Slot): https://${{ vars.AZURE_APP_SERVICE_NAME }}.azurewebsites.net"
