name: Azure Resource Deployment

on:
 workflow_dispatch:
   inputs:
     environment:
       description: 'Environment to deploy'
       required: true
       type: choice
       options:
         - dev
         - qa
         - prod
     
     module:
       description: "Terraform Module to deploy"
       required: true
       type: choice
       options:
         - vnet
         - vm
         - nsg
     
     auto-destroy:
        description: 'Destroy resources after apply'
        required: true
        type: choice
        options:
          - 'No'
          - 'Yes'

     delete-backend:
        description: 'Delete Terraform Backend after auto-destroy'
        required: true
        type: choice
        options:
          - 'No'
          - 'Yes'
       
jobs:
  terraform:
    name: azure-vm-deployment
    runs-on: ubuntu-latest
    defaults: 
     run: 
      working-directory: environments/${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az version

      # - name: Login to azure
      #   run: az login --use-device-code

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checking shell script for Backend
        run: ls *.sh

      - name: Making the script Executable
        run: |
          chmod +x *.sh
          sleep 10

      - name: Execute Shell Script for Terraform Backend
        run: ./*.sh
      
      - name: Install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
         
      - name: Configuring the Backend 
        run: |
          terraform init -backend-config="backend_config.tfvars"
          sleep 10
        working-directory: environments/${{ github.event.inputs.environment }}
        
      - name: Validating the script
        run: |
          terraform validate
          sleep 10
        working-directory: environments/${{ github.event.inputs.environment }}  
        
      - name: Planning the script 
        run: |          
          terraform plan -target=module.${{ github.event.input.module }} -var-file="${{ github.event.inputs.environment }}.tfvars" 
          sleep 10
        working-directory: environments/${{ github.event.inputs.environment }}
        
      - name: Applying the script
        run: 
          terraform apply -target=module.${{ github.event.input.module }} -var-file="${{ github.event.inputs.environment }}.tfvars"
          sleep 60
        working-directory: environments/${{ github.event.inputs.environment }}

      - name: Destroy Resources
        if: ${{ github.event.inputs.auto-destroy == 'true' }}
        run: |        
         echo "Waiting before destroying resources..."
         sleep 60
         terraform destroy -target=module.${{ github.event.input.module }} -var-file="${{ github.event.inputs.environment }}.tfvars"
        working-directory: environments/${{ github.event.inputs.environment }}

      - name: Delete Terraform backend
        if: ${{ github.event.inputs.delete-backend == 'Yes' }}
        run: |
          echo "Deleting Terraform Backend: $STORAGE_ACCOUNT"
          az storage account delete \
           --name "$STORAGE_ACCOUNT" \
           --resource-group "RESOURCE_GROUP" \
           --yes
        env:
          STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
          RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
           
          
      
