name: Azure VM Deployment

on:
 workflow_dispatch:
   inputs:
     environment:
       description: 'Environment to deploy'
       required: true
       type: choice
       options:
         - dev
         - qa
         - prod

     auto-destroy:
        description: 'Destroy resources after apply'
        required: true
        type: choice
        options:
          - 'false'
          -  'true'
       
jobs:
  terraform:
    name: azure-vm-deployment
    runs-on: self-hosted
    defaults: 
     run: 
      working-directory: environments/${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az version

      - name: Login to azure
        run: az login --use-device-code

      - name: Checking shell script for Backend
        run: ls *.sh

      - name: Making the script Executable
        run: |
          chmod +x *.sh
          sleep 10

      - name: Execute Shell Script
        run: ./*.sh
      
      - name: Install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
         
      - name: Configuring the Backend 
        run: |
          terraform init -backend-config="backend_config.tfvars"
          sleep 10
        
      - name: Validating the script
        run: | 
          terraform validate
          sleep 10
          
      - name: Planning the script 
        run: |
          terraform plan -var-file="${{ github.event.inputs.environment }}.tfvars"
          sleep 10

      - name: Applying the script
        run: |
          terraform apply -var-file="${{ github.event.inputs.environment }}.tfvars"
          sleep 60

      - name: Destroy Resources
        if: ${{ github.event.inputs.auto-destroy == 'true' }}
        run: |
         echo "Waiting before destroying resources..."
         sleep 60
         terraform destroy -var-file="${{ github.event.inputs.environment }}.tfvars"
